os:
  - linux
language:
  - python
python:
  - "3.4"
  - "3.5"
install:
  - pip install pytest
  - pip install python-coveralls
script:
  - py.test model.py --pep8 coveralls -v --cov coveralls
after_success:
  - coveralls
