os:
  - linux
language:
  - python
python:
  - "3.4"
  - "3.5"
install:
  - pip install pytest
  - pip install coveralls
script:
  - py.test model.py
  - coverage run model.py
after_success:
  - coveralls
